Adding an exit part to i3-switch

diff --git a/i3-switch b/i3-switch
--- a/i3-switch
+++ b/i3-switch
@@ -1,6 +1,10 @@
 #!/bin/bash
 DISTRO=$(cat /etc/os-release | grep "^NAME")
 
+if ! [[ -d /home/fusion809/.i3 ]]; then
+    printf "i3 directory not found\n" ; exit
+fi
+
 if [[ $DISTRO == "openSUSE"* ]]; then
     git -C /home/fusion809/.i3 checkout opensuse
 elif [[ $DISTRO == "Arch"* ]]; then
