Improvement, hopefully

diff --git a/usr/local/bin/openra-build b/usr/local/bin/openra-build
--- a/usr/local/bin/openra-build
+++ b/usr/local/bin/openra-build
@@ -2,29 +2,29 @@
 cd /home/fusion809/GitHub/mine/packaging/OpenRA || exit
 # Check for git
 if ! command -v git > /dev/null 2>&1; then
-    zenity --error --text="git not found, please add it to system path, presumably after installing it." --title="Error!" && exit
+	zenity --error --text="git not found, please add it to system path, presumably after installing it." --title="Error!" && exit
 fi
 # Check for make
 if ! command -v make > /dev/null 2>&1; then
-    zenity --error --text="make is missing, please add it to system path, command -v will likely be after you install it." --title="Error!" && exit
+	zenity --error --text="make is missing, please add it to system path, command -v will likely be after you install it." --title="Error!" && exit
 fi
 
 # Check for mono
 if ! command -v mono > /dev/null 2>&1; then
-    zenity --error --text="mono is missing, please add it to system path, command -v will likely be after you install it." --title="Error!" && exit
+	zenity --error --text="mono is missing, please add it to system path, command -v will likely be after you install it." --title="Error!" && exit
 fi
 
 # Check for Lua 5.1 libraries
 if ! find /usr/lib* /lib* -name "liblua*5*1*.so*" -quit > /dev/null 2>&1 ; then
-    zenity --error --text="Lua 5.1 libs are not found in /usr/lib/x86_64-linux-gnu, /lib64 or /usr/lib64. If they are installed somewhere else, but in LD_LIBRARY_PATH, feel free to ignore this warning, otherwise install these libraries please" --title="Error!" && exit
+	zenity --error --text="Lua 5.1 libs are not found in /usr/lib/x86_64-linux-gnu, /lib64 or /usr/lib64. If they are installed somewhere else, but in LD_LIBRARY_PATH, feel free to ignore this warning, otherwise install these libraries please" --title="Error!" && exit
 fi
 
 if ! find /lib* /usr/lib* -name "libopenal*" -quit > /dev/null 2>&1 ; then
-    zenity --error --text="OpenAL libraries not found, please install them." --title="Error!" && exit
+	zenity --error --text="OpenAL libraries not found, please install them." --title="Error!" && exit
 fi
 
 if ! find /lib* /usr/lib* -name "libSDL2*.so*" -quit > /dev/null 2>&1 ; then
-    zenity --error --text="SDL2 libraries not found, please install them." --title="Error!" && exit
+	zenity --error --text="SDL2 libraries not found, please install them." --title="Error!" && exit
 fi
 #printf "Updating my OpenRA fork...\n"
 
@@ -55,26 +55,25 @@ fi
 
 cd /home/fusion809/GitHub/others/OpenRA || exit
 commco=$(git rev-list --branches bleed --count)
-
-VERSION=$(cat /usr/lib/openra/VERSION)
+export DEST=$HOME/.local
+VERSION=$(cat $DEST/lib/openra/VERSION)
 
 if [[ $VERSION == "bleed-$commco" ]]; then
-    printf "At the latest commit already mate!\n" ; exit
+	printf "At the latest commit already mate!\n" ; exit
 fi
 
 if ! [[ -f /usr/bin/openra-ra ]] || [[ -f /usr/lib/openra/method ]] ; then
-    zenity --error --text="OpenRA is going to be updated to commit $commco" --title="Warning!"
-    if ! [[ $1 == "install" ]]; then
-         make clean
-    fi
-    make version VERSION="bleed-$commco"
-    echo "Manually build" | sudo tee -a  /usr/lib/openra/method
-    make
-    sudo make prefix=/usr install-core
-    sudo make prefix=/usr install-linux-shortcuts
-    sudo make prefix=/usr install-linux-mime
-    sudo make prefix=/usr install-man-page
-    sudo rm /usr/lib/openra/*.sh
-    sudo mkdir -p /var/games/openra/ModMetadata/
-    git stash
+	zenity --error --text="OpenRA is going to be updated to commit $commco" --title="Warning!"
+	if ! [[ $1 == "install" ]]; then
+		make clean
+	fi
+	make version VERSION="bleed-$commco"
+	echo "Manually build" | tee -a  $DEST/lib/openra/method
+	make
+	make prefix=/ install-core DESTDIR=$DEST
+	make prefix=/ install-linux-shortcuts DESTDIR=$DEST
+	make prefix=/ install-linux-mime DESTDIR=$DEST
+	make prefix=/ install-man-page DESTDIR=$DEST
+	rm $DEST/lib/openra/*.sh
+	git stash
 fi
