Adding OpenAL and SDL2 checks to openra-build

diff --git a/usr/local/bin/openra-build b/usr/local/bin/openra-build
--- a/usr/local/bin/openra-build
+++ b/usr/local/bin/openra-build
@@ -30,6 +30,32 @@ if ! ls /usr/lib/x86_64-linux-gnu/liblua5.1.so* > /dev/null 2>&1 ; then
          fi
     fi
 fi
+
+if ! ls /usr/lib64/libopenal.so* > /dev/null 2>&1 ; then
+    if ! ls /usr/lib/libopenal.so* > /dev/null 2>&1 ; then
+	 if ! /lib64/libopenal.so* > /dev/null 2>&1 ; then
+              if ! /lib/libopenal.so* > /dev/null 2>&1 ; then
+		   if ! /usr/lib/x86_64-linux-gnu/libopenal.so* > /dev/null 2>&1 ; then
+			zenity --error --text="OpenAL libraries not found, please install them." --title="Error!" && exit
+	           fi
+	      fi
+	 fi
+    fi
+fi
+
+if ! ls /usr/lib64/libSDL2*.so* > /dev/null 2>&1 ; then
+    if ! ls /usr/lib/libSDL2*.so* > /dev/null 2>&1 ; then
+	 if ! /lib64/libSDL2*.so* > /dev/null 2>&1 ; then
+              if ! /lib/libSDL2*.so* > /dev/null 2>&1 ; then
+		   if ! /usr/lib/x86_64-linux-gnu/libSDL2*.so* > /dev/null 2>&1 ; then
+			zenity --error --text="SDL2 libraries not found, please install them." --title="Error!" && exit
+	           fi
+	      fi
+	 fi
+    fi
+fi
+#printf "Updating my OpenRA fork...\n"
+
 #printf "Updating my OpenRA fork...\n"
 #git pull upstream bleed -q
 
