Adding SDL2 & OpenAL check to openra-build-cli, fixing checks for libraries by getting them to use find with the --quit option

diff --git a/usr/local/bin/openra-build b/usr/local/bin/openra-build
--- a/usr/local/bin/openra-build
+++ b/usr/local/bin/openra-build
@@ -15,44 +15,16 @@ if ! `which mono > /dev/null 2>&1`; then
 fi
 
 # Check for Lua 5.1 libraries
-if ! ls /usr/lib/x86_64-linux-gnu/liblua5.1.so* > /dev/null 2>&1 ; then
-    if ! [[ -f /lib64/liblua5.1.so ]]; then
-         if ! [[ -f /usr/lib64/liblua5.1.so.0 ]]; then
-              if ! [[ -f /usr/lib64/liblua.so.5.1.5 ]]; then
-                   if ! [[ -f /usr/lib64/liblua.so.5.1 ]]; then
-			     if ! [[ -f /usr/lib/liblua5.1.so.5.1 ]]; then
-				  if ! [[ -f /usr/lib64/liblua-5.1.so ]]; then
-                                       zenity --error --text="Lua 5.1 libs are not found in /usr/lib/x86_64-linux-gnu, /lib64 or /usr/lib64. If they are installed somewhere else, but in LD_LIBRARY_PATH, feel free to ignore this warning, otherwise install these libraries please" --title="Error!" && exit
-				  fi
-		             fi
-                   fi
-              fi
-         fi
-    fi
+if ! find /usr/lib* /lib* -name "liblua*5*1*.so*" --quit > /dev/null 2>&1 ; then
+    zenity --error --text="Lua 5.1 libs are not found in /usr/lib/x86_64-linux-gnu, /lib64 or /usr/lib64. If they are installed somewhere else, but in LD_LIBRARY_PATH, feel free to ignore this warning, otherwise install these libraries please" --title="Error!" && exit
 fi
 
-if ! ls /usr/lib64/libopenal.so* > /dev/null 2>&1 ; then
-    if ! ls /usr/lib/libopenal.so* > /dev/null 2>&1 ; then
-	 if ! /lib64/libopenal.so* > /dev/null 2>&1 ; then
-              if ! /lib/libopenal.so* > /dev/null 2>&1 ; then
-		   if ! /usr/lib/x86_64-linux-gnu/libopenal.so* > /dev/null 2>&1 ; then
-			zenity --error --text="OpenAL libraries not found, please install them." --title="Error!" && exit
-	           fi
-	      fi
-	 fi
-    fi
+if ! find /lib* /usr/lib* -name "libopenal*" --quit > /dev/null 2>&1 ; then
+    zenity --error --text="OpenAL libraries not found, please install them." --title="Error!" && exit
 fi
 
-if ! ls /usr/lib64/libSDL2*.so* > /dev/null 2>&1 ; then
-    if ! ls /usr/lib/libSDL2*.so* > /dev/null 2>&1 ; then
-	 if ! /lib64/libSDL2*.so* > /dev/null 2>&1 ; then
-              if ! /lib/libSDL2*.so* > /dev/null 2>&1 ; then
-		   if ! /usr/lib/x86_64-linux-gnu/libSDL2*.so* > /dev/null 2>&1 ; then
-			zenity --error --text="SDL2 libraries not found, please install them." --title="Error!" && exit
-	           fi
-	      fi
-	 fi
-    fi
+if ! find /lib* /usr/lib* -name "libSDL2*.so*" --quit > /dev/null 2>&1 ; then
+    zenity --error --text="SDL2 libraries not found, please install them." --title="Error!" && exit
 fi
 #printf "Updating my OpenRA fork...\n"
 
diff --git a/usr/local/bin/openra-build-cli b/usr/local/bin/openra-build-cli
--- a/usr/local/bin/openra-build-cli
+++ b/usr/local/bin/openra-build-cli
@@ -15,18 +15,16 @@ if ! `which mono > /dev/null 2>&1`; then
 fi
 
 # Check for Lua 5.1 libraries
-if ! [[ -f /usr/lib/x86_64-linux-gnu/liblua5.1.so ]] ; then
-    if ! [[ -f /lib64/liblua5.1.so ]]; then
-         if ! [[ -f /usr/lib64/liblua5.1.so.0 ]]; then
-              if ! [[ -f /usr/lib64/liblua.so.5.1.5 ]]; then
-                   if ! [[ -f /usr/lib64/liblua.so.5.1 ]]; then
-			     if ! [[ -f /usr/lib/liblua5.1.so.5.1 ]]; then
-                                  printf "Lua 5.1 libs are not found in /usr/lib/x86_64-linux-gnu, /lib64 or /usr/lib64. If they are installed somewhere else, but in LD_LIBRARY_PATH, feel free to ignore this warning, otherwise install these libraries please\n"
-		             fi
-                   fi
-              fi
-         fi
-    fi
+if ! find /usr/lib* /lib* -name "liblua*5*1*.so*" --quit > /dev/null 2>&1 ; then
+    printf "Lua 5.1 libs are not found in /usr/lib/x86_64-linux-gnu, /lib64 or /usr/lib64. If they are installed somewhere else, but in LD_LIBRARY_PATH, feel free to ignore this warning, otherwise install these libraries please\n"
+fi
+
+if ! find /lib* /usr/lib* -name "libopenal*" --quit > /dev/null 2>&1 ; then
+    printf "OpenAL libraries not found, please install them.\n" && exit
+fi
+
+if ! find /lib* /usr/lib* -name "libSDL2*.so*" --quit > /dev/null 2>&1 ; then
+    printf "SDL2 libraries are not found, please install them.\n" && exit
 fi
 #printf "Updating my OpenRA fork...\n"
 #git pull upstream bleed -q
