Minor ShellCheck fixes, adding gsoftbn and gsoftbnz scripts for checking gnome-software-bleed status

diff --git a/usr/local/bin/openra-build b/usr/local/bin/openra-build
--- a/usr/local/bin/openra-build
+++ b/usr/local/bin/openra-build
@@ -1,17 +1,17 @@
 #!/bin/bash
-cd /home/fusion809/GitHub/mine/packaging/OpenRA
+cd /home/fusion809/GitHub/mine/packaging/OpenRA || exit
 # Check for git
-if ! `which git > /dev/null 2>&1`; then
+if ! command -v git > /dev/null 2>&1; then
     zenity --error --text="git not found, please add it to system path, presumably after installing it." --title="Error!" && exit
 fi
 # Check for make
-if ! `which make > /dev/null 2>&1`; then
-    zenity --error --text="make is missing, please add it to system path, which will likely be after you install it." --title="Error!" && exit
+if ! command -v make > /dev/null 2>&1; then
+    zenity --error --text="make is missing, please add it to system path, command -v will likely be after you install it." --title="Error!" && exit
 fi
 
 # Check for mono
-if ! `which mono > /dev/null 2>&1`; then
-    zenity --error --text="mono is missing, please add it to system path, which will likely be after you install it." --title="Error!" && exit
+if ! command -v mono > /dev/null 2>&1; then
+    zenity --error --text="mono is missing, please add it to system path, command -v will likely be after you install it." --title="Error!" && exit
 fi
 
 # Check for Lua 5.1 libraries
@@ -53,7 +53,7 @@ fi
 #git push origin $commn
 #printf "Pushing to bleed branch...\n"
 
-cd /home/fusion809/GitHub/others/OpenRA
+cd /home/fusion809/GitHub/others/OpenRA || exit
 commco=$(git rev-list --branches bleed --count)
 
 VERSION=$(cat /usr/lib/openra/VERSION)
diff --git a/usr/local/bin/openra-build-cli b/usr/local/bin/openra-build-cli
--- a/usr/local/bin/openra-build-cli
+++ b/usr/local/bin/openra-build-cli
@@ -2,18 +2,18 @@
 cd /data/GitHub/others/OpenRA || ( printf "/home/fusion809/GitHub/others/OpenRA doesn't exist mate, therefore I am exiting\!" && exit )
 
 # Check for git
-if ! which git > /dev/null 2>&1; then
+if ! command -v git > /dev/null 2>&1; then
     printf "git not found, please add it to system path, presumably after installing it.\n"
 fi
 
 # Check for make
-if ! which make > /dev/null 2>&1; then
-    printf "make is missing, please add it to system path, which will likely be after you install it.\n"
+if ! command -v make > /dev/null 2>&1; then
+    printf "make is missing, please add it to system path, command -v will likely be after you install it.\n"
 fi
 
 # Check for mono
-if ! which mono > /dev/null 2>&1; then
-    printf "mono is missing, please add it to system path, which will likely be after you install it.\n"
+if ! command -v mono > /dev/null 2>&1; then
+    printf "mono is missing, please add it to system path, command -v will likely be after you install it.\n"
 fi
 
 # Check for Lua 5.1 libraries
diff --git a/usr/local/bin/scrnshot b/usr/local/bin/scrnshot
--- a/usr/local/bin/scrnshot
+++ b/usr/local/bin/scrnshot
@@ -12,9 +12,9 @@ Y=$(calc Y)
 
 OS=$(cat /etc/os-release | grep "^NAME" | cut -d '=' -f 2 | cut -d '"' -f 2 | sed 's/ /_/g' | head -n 1)
 VERSION=$(cat /etc/os-release | grep VERSION_ID | cut -d '=' -f 2 | cut -d '"' -f 2)
-if ! `which import > /dev/null 2>&1`; then
-    if `which zenity > /dev/null 2>&1`; then
-         zenity --error --text="import command not found, please which if ImageMagick is installed, if not, install it, otherwise add the import command to your system PATH!" --title="Error!"
+if ! command -v import > /dev/null 2>&1; then
+    if command -v zenity > /dev/null 2>&1; then
+         zenity --error --text="import command not found, please command -v if ImageMagick is installed, if not, install it, otherwise add the import command to your system PATH!" --title="Error!"
     fi
 fi
 
