Adding Mono and & Lua checks to openra-build

diff --git a/usr/local/bin/openra-build b/usr/local/bin/openra-build
--- a/usr/local/bin/openra-build
+++ b/usr/local/bin/openra-build
@@ -1,11 +1,27 @@
 #!/bin/bash
 cd /home/fusion809/GitHub/mine/packaging/OpenRA
+# Check for git
 if ! `which git > /dev/null 2>&1`; then
     printf "git not found, please add it to system path, presumably after installing it.\n" && exit
-elif ! `which make > /dev/null 2>&1`; then
+fi
+# Check for make
+if ! `which make > /dev/null 2>&1`; then
     printf "make is missing, please add it to system path, which will likely be after you install it.\n" && exit
 fi
 
+# Check for mono
+if ! `which mono > /dev/null 2>&1`; then
+    printf "mono is missing, please add it to system path, which will likely be after you install it.\n" && exit
+fi
+
+# Check for Lua 5.1 libraries
+if ! [[ -f /usr/lib/x86_64-linux-gnu/liblua5.1.so ]] ; then
+    if ! [[ -f /lib64/liblua5.1.so ]]; then
+         if ! [[ -f /usr/lib64/liblua5.1.so.0 ]]; then
+              printf "Lua 5.1 libs are not found in /usr/lib/x86_64-linux-gnu, /lib64 or /usr/lib64. If they are installed somewhere else, but in LD_LIBRARY_PATH, feel free to ignore this warning, otherwise install these libraries plesee" && exit
+         fi
+    fi
+fi
 #printf "Updating my OpenRA fork...\n"
 #git pull upstream bleed -q
 
