Fixing some ShellCheck warnings

diff --git a/usr/local/bin/scrnshot b/usr/local/bin/scrnshot
--- a/usr/local/bin/scrnshot
+++ b/usr/local/bin/scrnshot
@@ -10,16 +10,21 @@ D=$(calc d)
 m=$(calc m)
 Y=$(calc Y)
 
-OS=$(cat /etc/os-release | grep "^NAME" | cut -d '=' -f 2 | cut -d '"' -f 2 | sed 's/ /_/g' | head -n 1)
-VERSION=$(cat /etc/os-release | grep VERSION_ID | cut -d '=' -f 2 | cut -d '"' -f 2)
+OS=$(grep "^NAME" < /etc/os-release | cut -d '=' -f 2 | cut -d '"' -f 2 | sed 's/ /_/g' | head -n 1)
+VERSION=$(grep "^VERSION_ID" < /etc/os-release | cut -d '=' -f 2 | cut -d '"' -f 2)
+
 if ! command -v import > /dev/null 2>&1; then
-    if command -v zenity > /dev/null 2>&1; then
-         zenity --error --text="import command not found, please command -v if ImageMagick is installed, if not, install it, otherwise add the import command to your system PATH!" --title="Error!"
-    fi
+	if command -v zenity > /dev/null 2>&1; then
+		zenity --error --text="import command not found, please command -v if ImageMagick is installed, if not, install it, otherwise add the import command to your system PATH!" --title="Error!"
+	fi
+fi
+
+if ! [[ -d "/home/fusion809/Pictures/Screenshots/${XDG_SESSION_DESKTOP}/${OS}-${VERSION}" ]]; then
+	mkdir -p "/home/fusion809/Pictures/Screenshots/${XDG_SESSION_DESKTOP}/${OS}-${VERSION}"
 fi
 
 if [[ -n $VERSION ]] ; then
-    import -window root -frame -silent "/home/fusion809/Pictures/Screenshots/${XDG_SESSION_DESKTOP}/Screenshot_${OS}_${VERSION}_${Y}${m}${D}_${H}${M}${S}.png" || zenity --error --text="Screenshot command:\n<span bgcolor='#CCCCCC'><tt>import -window root -frame -silent \"/home/fusion809/Pictures/Screenshots/${XDG_SESSION_DESKTOP}/Screenshot_${OS}_${VERSION}_${Y}${m}${D}_${H}${M}${S}.png\"</tt></span>" --width=1000 
+	import -window root -frame -silent "/home/fusion809/Pictures/Screenshots/${XDG_SESSION_DESKTOP}/${OS}-${VERSION}/Screenshot_${Y}${m}${D}_${H}${M}${S}.png" || zenity --error --text="Screenshot command:\n<span bgcolor='#CCCCCC'><tt>import -window root -frame -silent \"/home/fusion809/Pictures/Screenshots/${XDG_SESSION_DESKTOP}/${OS}-${VERSION}/Screenshot_${Y}${m}${D}_${H}${M}${S}.png\"</tt></span>" --width=1000 
 else
-    import -window root -frame -silent "/home/fusion809/Pictures/Screenshots/${XDG_SESSION_DESKTOP}/Screenshot_${OS}_${Y}${m}${D}_${H}${M}${S}.png" || zenity --error --text="Screenshot command:\n<span bgcolor='#CCCCCC'><tt>import -window root -frame -silent \"/home/fusion809/Pictures/Screenshots/${XDG_SESSION_DESKTOP}/Screenshot_${OS}_${Y}${m}${D}_${H}${M}${S}.png\"</tt></span>" --width=1000 
+	import -window root -frame -silent "/home/fusion809/Pictures/Screenshots/${XDG_SESSION_DESKTOP}/${OS}-${VERSION}/Screenshot_${Y}${m}${D}_${H}${M}${S}.png" || zenity --error --text="Screenshot command:\n<span bgcolor='#CCCCCC'><tt>import -window root -frame -silent \"/home/fusion809/Pictures/Screenshots/${XDG_SESSION_DESKTOP}/${OS}-${VERSION}/Screenshot_${Y}${m}${D}_${H}${M}${S}.png\"</tt></span>" --width=1000 
 fi
