Making scrnshot work on other desktops

diff --git a/usr/local/bin/scrnshot b/usr/local/bin/scrnshot
--- a/usr/local/bin/scrnshot
+++ b/usr/local/bin/scrnshot
@@ -11,5 +11,11 @@ m=$(calc m)
 Y=$(calc Y)
 
 OS=$(cat /etc/os-release | grep "^ID" | cut -d '=' -f 2 | head -n 1)
+OS=${OS^}
+if ! `which import > /dev/null 2>&1`; then
+    if `which zenity > /dev/null 2>&1`; then
+         zenity --error --text="import command not found, please which if ImageMagick is installed, if not, install it, otherwise add the import command to your system PATH!" --title="Error!"
+    fi
+fi
 
-/usr/bin/import -window root -frame -silent "/home/fusion809/Pictures/Screenshots/i3/Screenshot_${OS}_${Y}${m}${D}_${H}${M}${S}.png"
+import -window root -frame -silent "/home/fusion809/Pictures/Screenshots/${XDG_SESSION_DESKTOP}/Screenshot_${OS}_${Y}${m}${D}_${H}${M}${S}.png" || zenity --error --text="Screenshot command:\n<span bgcolor='#CCCCCC'><tt>import -window root -frame -silent \"/home/fusion809/Pictures/Screenshots/${XDG_SESSION_DESKTOP}/Screenshot_${OS}_${Y}${m}${D}_${H}${M}${S}.png\"</tt></span>" --width=1000 
